### ISSUE TITLE
Hints not working on Instagram

### ISSUE THREAD

**Issue by gsbabil** [cmcaine/tridactyl#136] opened 2017-11-25 19:19 UTC
Hints are currently not working on Instagram pages. The links get highlighted, but there is no hint-keys next to the links as expected. Please see the attached screenshot. Thank you.

![screenshot-2017-11-26 babil gsbabil instagram photos and videos](https://user-images.githubusercontent.com/1061108/33233893-b8a36b7e-d271-11e7-8243-fb4ade66050d.png)

**Comment by bovine3dom** [comment] 2017-11-25 19:22
Issue confirmed - people can use https://www.instagram.com/jacob_rees_mogg/?hl=en to test to avoid having to sign up.

**Comment by glacambre** [comment] 2017-11-28 07:29
I took a quick look at where the problem might come from, it seems that the "hintHost" div is infected by instagram's CSS and ends up being displayed "off-screen". This can be fixed by changing its css and forcing it to be displayed at the top of the screen (`position: initial;`, `position: static;` or `position: unset;`), however another issue arises then: when scrolling, hints won't be displayed at the right place anymore.
Fixing this might require either to put hints inside the hinted elements (but it could break javascript/css on a lot of websites) or refresh hint positions every time the page moves (this seems to be the approach Pentadactyl uses).

**Closed** 2017-11-28 17:19 UTC
Labels: site specific

**Comment by cmcaine** [comment] 2017-11-28 17:35
Hints still don't work for images, but I don't see any way we can detect that they're clickable, besides special casing instagram.

If someone wants to work on special casing for instagram (possibly for react apps in general?), that's welcome and a PR would be likely to be accepted.

To my knowledge there's no way for us to list event handlers of an element. There used to be a method in Gecko to do it that extension code could access, but it's not exposed to WebExtensions (if it even still works). See https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIEventListenerInfo
