### ISSUE TITLE
Hints in 'dark' theme revert to the default theme under certain conditions.

### ISSUE THREAD

**Issue by antonva** [cmcaine/tridactyl#543] opened 2018-05-16 11:09 UTC
I'm not quite sure what's happening here, I can't get it to reproduce all of the time but the sites mentioned in the steps have so far been consistent.
Steps to reproduce: :

- `set theme dark`
- visit any of {github, reddit, hackernews}
- press `f`
- enter any character that is a first letter in a hint
- the remaining hints are now styled by the default style

**Comment by glacambre** [comment] 2018-05-16 11:15
Looks like you're the first person to use the dark theme, this bug must have been here for a long time :)

This will probably be fixed by https://github.com/cmcaine/tridactyl/pull/537

**Comment by cmcaine** [comment] 2018-05-16 11:29
We tested this when themes were introduced. I can't reproduce on 1.12.0-11-g70ed5d1 with hintfiltermode default or vimperator-reflow.

Themes are changing so I guess it's moot.

**Comment by bovine3dom** [comment] 2018-05-16 12:44
I can't reproduce this either :S

**Comment by cmcaine** [comment] 2018-05-16 23:16
I can also reproduce on 1.12.0-9-g82c4348 (latest AMO)

**Comment by caputchinefrobles** [comment] 2018-05-22 19:19
I think removing theme logic from hinting.ts fixed this. I was not able to reproduce it anymore with filterhintmode = simple. 

The problem was that when you hit the first key for filtering, hints not matching the filter get hidden removing TridactylHintElem from the hint element, but also TridactylThemeDark from :root, which caused hints matching the filter to show on default theme. 

Further confirmation needed.

**Closed** 2018-05-23 18:16 UTC
