### ISSUE TITLE
Open about: URLs on OSX

### ISSUE THREAD

**Issue by divad42** [cmcaine/tridactyl#538] opened 2018-05-15 01:22 UTC
It is not possible to open firefox's about: URLs, such as about:support or about:config, using the :open command.

**Comment by bovine3dom** [comment] 2018-05-15 03:38
It is possible, but if you have the native messenger installed, although it will open a new tab (see #433).

Tridactyl should ask you to install the native messenger if you try to open an about: URI. What :version are you using?

**Comment by bovine3dom** [comment] 2018-05-16 09:04
Oh, it's not supported on OSX as `firefox --newtab` is broken and won't be fixed by Mozilla. I think there's an issue open for it - we need to write some applescript that does the equivalent.

Sorry, I totally forgot...

**Comment by bovine3dom** [comment] 2018-05-16 14:05
Duplicate of #451.

**Closed by bovine3dom** 2018-05-16 14:05 UTC
Labels: good first issue, nativemessenger, osx
