### ISSUE TITLE
Sane subset of behaviour should be enabled on bare image tabs

### ISSUE THREAD

**Issue by reversebreak** [cmcaine/tridactyl#692] opened 2018-06-17 04:45 UTC
If you open an image file in its own tab, Tridactyl effectively stops working until you tab away from it.
This applies for all keyboard shortcuts whatsoever.

Tridactyl should have some sane subset of behaviour enabled on bare image tabs.  Of course, some of the concepts don't quite work there (there's no links to hint etc) but for a start gt gT d o etc should all work.

**Comment by bovine3dom** [comment] 2018-06-17 08:54
Could you give us a link to the page in question? I thought this was fixed.

`set csp clobber` might fix it for you.

**Comment by reversebreak** [comment] 2018-06-17 09:05
Using Firefox 60.0.2 64-bit and the latest stable Tridactyl from AMO,
https://raw.githubusercontent.com/cmcaine/tridactyl/master/doc/AMO_screenshots/trishowcase.gif
I got there by playing around with extended hints on the base Tridactyl page - specifically the `;I` hint.

**Comment by reversebreak** [comment] 2018-06-17 09:06
Oh, sorry, and what does 
set csp clobber 
do?

**Comment by glacambre** [comment] 2018-06-17 09:28
`set csp clobber` rewrites the [Content Security Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) in order to allow Tridactyl to work on some pages.

The reason Tridactyl doesn't work on the link you provided is because the CSP blocks Tridactyl. Using `set csp clobber` fixes this issue.

**Comment by antonva** [comment] 2018-06-17 09:49
Might be proper to point out that `set csp clobber` will effectively disable CSP and not just whitelist/enable Tridactyl. It's very much a use at your own risk feature.

**Comment by bovine3dom** [comment] 2018-06-17 10:06
Closing as duplicate of #109.

Mozilla say that they will fix this eventually, but in the meantime our CSP setting can fix it and the cost of slightly reduced security.

**Closed by bovine3dom** 2018-06-17 10:06 UTC
