### ISSUE TITLE
sanitise tridactylsync timing error breaks RC-file config

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [cmcaine/tridactyl#686] opened 2018-06-15 04:30 UTC
Run this command to clear out the config,

    :sanitise tridactylsync tridactyllocal

Save this config to `~/.tridactylrc`:

    set theme dark
    sanitise tridactylsync
    set theme greenmat

Then `:restart`.

At least on my machine, with the betas, this reproducibly:

1. Initially displays white (due to the manual `sanitise`, `theme = default`)
2. very briefly flashes dark,
3. turns green for a bit,
4. then **turns white again**.

Due to this bug, `tridactylrc` isn't working for me. Any configuration settings I set seem to have
no effect, as long as the suggested line `sanitise tridactylsync tridactyllocal` appears anywhere in
my config file — presumably because `sanitise tridactylsync` is resetting all of the config
variables I've set, immediately *after* the config file is finished being evaluated.

(Of note, `sanitise tridactyllocal` doesn't display the same bug — for the moment, that's what I'm
using in my `tridactylrc`.)

**Comment by ELLIOTTCABLE** [comment] 2018-06-15 04:34
I suspect relatedly, after a `:sanitise tridactylsync` (even without any of the above preparation), `:source` yields `# TypeError: obj is undefined`.

**Comment by glacambre** [comment] 2018-06-15 04:38
Most probably a duplicate of https://github.com/cmcaine/tridactyl/issues/322 .

**Comment by ELLIOTTCABLE** [comment] 2018-06-15 04:41
@glacambre Sure looks like it!

Meanwhile, things like this would be a lot easier to spot/debug, if Tridactyl showed errors in commands executed via the rc-file. Why wouldn't I see the same `# TypeError: obj is undefined` error via the rcfile?

(Just a thought: maybe you should ship the Tridactyl betas with the error-reporting level cranked up by one or two levels? People opting into the betas are presumably a little more ready to report bugs, and help debug, etc …)

**Comment by bovine3dom** [comment] 2018-06-15 05:49
> Meanwhile, things like this would be a lot easier to spot/debug, if Tridactyl showed errors in commands executed via the rc-file. Why wouldn't I see the same # TypeError: obj is undefined error via the rcfile?

Because I'm lazy and rather than trying to work out if an rc file exists I just try to source it anyway and ignore all errors. In my defense, I did think it was a terrible idea at the time.

**Closed** 2018-06-17 17:48 UTC
