### ISSUE TITLE
Weird commandline position

### ISSUE THREAD

**Issue by thmsaurel** [cmcaine/tridactyl#282] opened 2018-01-18 10:43 UTC
When I load this page,the command line is activated. When I open it manually it take the same position.

![2018-01-18_9-54-48](https://user-images.githubusercontent.com/5463836/35089204-88874e26-fc36-11e7-8c40-a7f0e2f527ec.jpg)

It doesn't seem to be due to any extensions that i have (I deactivated all of them (except tridactyl) and I always have the issue). 

Issued website: https://0x39b.fr

**Comment by johnbeard** [comment] 2018-01-19 21:34
Caused by `caffeine-theme.css` setting a CSS property `min-height: 200px;` on the command line `iframe`.

I imagine this can go in the pile with the other leaking CSS issues that might be solved by importing that CSS that clears external styling.

**Comment by cmcaine** [comment] 2018-02-03 02:53
Duplicate of #112

**Closed by cmcaine** 2018-02-03 02:53 UTC
