### ISSUE TITLE
VIM Find no longer working on Atlassian pages

### ISSUE THREAD

**Issue by wschmrdrNS** [cmcaine/tridactyl#295] opened 2018-01-26 14:53 UTC
Navigate to https://bitbucket.org/richardpenman/pywhois/overview
Attempt to use / to search

Doesn't work.

**Comment by bovine3dom** [comment] 2018-01-27 23:44
That's quite strange. `/` isn't anything to do with us, really. There could be a problem with how we whitelist `/` to ensure that it is passed through to the page.

When I get a minute, I need to test it on a vanilla Firefox profile to see if the issue is actually anything to do with Tridactyl...

**Comment by cmcaine** [comment] 2018-01-28 00:15
I suspect it's not us. Atlassian probably have their own find function
attached to /

**Comment by bovine3dom** [comment] 2018-01-28 12:32
Same behaviour with Tridactyl disabled. Closing as a bona fide not-our-fault.

**Closed by bovine3dom** 2018-01-28 12:32 UTC
