### ISSUE TITLE
When running `npm install` on Windows, shared-git-hooks throws an error when attempting to symlink

### ISSUE THREAD

**Issue by m0tive** [cmcaine/tridactyl#84] opened 2017-11-19 21:16 UTC
Possibly this should be a platform specific dependency? using [npm-platform-dependencies](https://www.npmjs.com/package/npm-platform-dependencies) maybe?

**Comment by m0tive** [comment] 2017-11-19 21:19
Well, I seem most of the rest of the build system assumes it's running on unix, so nevermind...

**Comment by bovine3dom** [comment] 2017-11-19 23:03
We'd like to support building on Windows eventually. This issue is probably a good place to keep track of progress towards that.

I think the main culprit right now is `sed` which is used in `:help`.

Windows Subsystem for Linux should work fine, by the way. You would install npm in both WSL and Windows, build in WSL, and just use the Windows npm to run web-ext.

**Comment by cmcaine** [comment] 2017-11-20 01:54
Are you trying to run in `cmd` or `cygwin`?

`scripts/` contains a bunch of shell scripts. If someone rewrites them as equally or better readable JS then we could merge that, but I'm not going to spend any time on it: the windows shell is awful and WSL should work fine.

**Comment by Bzly** [comment] 2017-11-20 03:34
@bovine3dom - surely #48 would be the place to do that?

**Comment by bovine3dom** [comment] 2017-11-20 09:27
Absolutely. Closed as duplicate of #48.

**Closed by bovine3dom** 2017-11-20 09:27 UTC
