### ISSUE TITLE
Clicking in the left hand pane of gmail stops keyevents being sent to Tridactyl

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#417] opened 2018-04-23 14:03 UTC

**Comment by cmcaine** [comment] 2018-04-26 08:17
Could not reproduce. Scrolling is really weird on gmail, though: are you testing with scrolling or some other function?

I used `:`, `o`, `f`.

**Comment by bovine3dom** [comment] 2018-04-26 08:41
I think I tried everything, and I had the debug console open and key events weren't being logged.

**Comment by bovine3dom** [comment] 2018-04-26 18:40
Reproducible - but you have to click in the "Hangouts" bit in the bottom left half of the pane.

**Comment by cmcaine** [comment] 2018-04-26 19:35
Cool. It's the same iframe issue. Closing as duplicate.

**Closed by cmcaine** 2018-04-26 19:35 UTC
Labels: site specific
