### ISSUE TITLE
How to have some URLs always in ignore mode?

### ISSUE THREAD

**Issue by benfitzg** [cmcaine/tridactyl#158] opened 2017-11-29 01:48 UTC
Hi

I'd love to have figured this out and submitted a PR, assuming this feature is missing, however I'm finding it tough to comprehend the event loop / entry points.

Is it possible to ignore some URLs? How can this plugin be continuously in "ignore" mode for a given url regexp, configured "somewhere".

**Comment by bovine3dom** [comment] 2017-11-29 08:24
Essentially, you want to make an `aucmd`.

You would probably add a function that executes all aucmds that match window.location.href, maybe just at the end of a content script, or as an event listener to document load.

Then one of those excmds can be "enter ignore mode". There's a small caveat in that document load also calls normal mode, but you can probably take that out.

That's the easy bit - the real hold up is that we don't have user configuration yet, and we are reluctant to add more special cases like `bind`, because eventually it will need to be migrated to whatever we decide on in the end.

**Comment by cmcaine** [comment] 2017-11-29 11:13
A quick way to do it would be to store an array of ignored URLs with state.ts and query that in keydown_content.ts (the only part of the code that receives real key events), or, perhaps better, in controller.ts (the code that decides which parser to send each key event to).

In controller.ts you'd just add something to the `onBeforeNavigate` listener to change mode to ignore if the new URL matched one of your patterns.

There's a known race condition where the onBeforeNavigate handler can edit the state after the user has already entered a new mode on the new page. That's pretty rubbish, and we intend to fix it by eventually moving mode, parsers and controller into the content script. We'll then just have utility libraries and so on in the background.

As a quick fix, we'll probably move the onBeforeNavigate handler to the content script onDocumentLoad handler or something.

In terms of the current flow of control, keys are captured by keydown_content.ts, sent to keydown_background where they are then routed to the controller (`keydown_background.onKeydown.addListener(Controller.acceptKey)`). The controller has a list of 'parsers' to send the keyevent too. For the most part, these take an array of keyevents and either mutate the array (removing keys from the front that can't possibly match) or empty the array and return an exstr to exec (e.g. `scrollline 10`). The hint and gobble mode parsers also have a default action that allows them to consume a keyevent and perform some arbitrary, potentially non-exstr, action.

**Comment by benfitzg** [comment] 2017-11-30 04:03
Thanks for taking the time to reply, I'll have to spend some time to grok the above but it's a great start.

**Comment by benfitzg** [comment] 2017-12-06 03:14
Okay had a first pop at this, javascript / typescript is new to me, as are browser hooks although I have plenty of experience in async programming so not a total car crash.

My first thought on this is that you have one variable to represent state, therefore it seems to me that you need to be reassessing the desired state every time you move from one tab to another, not just on document reload via `onBeforeNavigate`. My usage pattern for something like vimperator was to have some tabs which have their own navigation support that is specific and therefore superior (RES on reddit, or the regular key bindings on twitter, for example). I want to return to that tab and find the "native" keybindings, then hop off to another tab and use it with tridactyl, then go back, and have the modes appear to stay the same.

Even then I think you have a problem because if you have a predefined list of sites to "ignore", what happens if you set a tab to ignore, leave that tab to a normal tab, then return back - it will check the urls to ignore, conclude that the mode should be `normal` and leave the user to have to set it back to ignore again. To me that seems a bit annoying. I guess you could solve this by pushing into more state tabs set to ignore, but then managing that could be painful.

Anyhow that's my $0.10 on first mucking around with this. I have ignore mode working but it gets reset on tab-hopping by this:

```
browser.webNavigation.onBeforeNavigate.addListener(async function (details) {                                                                          
    if (details.tabId == await activeTabId()) {                                                                                                        
        state.mode = 'normal'                                                                                                                               
    }                                                                                                                                                  
})                
```

I'm confused about the purpose of the above, if anyone knows why it wants to do this and can explain?

Also sites which have addons like RES for reddit call `onBeforeNavigate` several times, first with reddit.com but then with redditmedia.com and finally with the UUID of the tridactyl plugin, so simply inspecting the URL doesn't work because the first callback matches but then subsequent ones reset back to `normal` as the url doesn't match. The only way I can see to fix this is to build a url filter and pass that as the second arg to `onBeforeNavigate` which then doesn't "see" these other urls.

Interesting stuff, I'm a newbie to web dev so some of the above may make you want to slap me. Go ahead.

**Comment by bovine3dom** [comment] 2018-02-02 15:16
@benfitzg I only just saw your comment, it must have been buried, sorry! Thanks for looking into it.

Versions greater than `1.7.3-82-gc178780` should have `autocmd` working, so you can "blacklist" a site with

`autocmd DocStart [site name] mode ignore`.

It will still revert to normal mode when you change tabs.

**Comment by cmcaine** [comment] 2018-02-03 01:56
(We're working on better autocmds, it sort of depends on per-page state)

**Comment by BoWuGit** [comment] 2018-02-04 03:37
@bovine3dom could you please explain this command a little More in detail？

`autocmd DocStart [site name] mode ignore`

I could not figure out how to use it.

And personally I think this functionality is very important, once implemented , I could happily change from vimium to tridactyl.

Thanks.

**Comment by bovine3dom** [comment] 2018-02-04 11:37
@BoWuGit firstly, you have to be using a recent beta release such that the output of :version is greater than or equal to 1.7.3-82.

Then, say I want Google to be in ignore mode, I would type `:autocmd DocStart google.co.uk mode ignore`.

An auto command is just a command that is executed every time an event matching some conditions occurs. The only event we support at the moment is DocStart, which corresponds to Firefox's "document_start". It is triggered every time a new page starts loading. The next argument is a condition the event must match. Currently, we just have that the URL must contain the supplied string.

The rest of the arguments are the excmd to execute. In our example "mode ignore" puts Tridactyl into ignore mode.

Does that help?

**Comment by BoWuGit** [comment] 2018-02-04 13:22
@bovine3dom thanks very much, I have understood it. 
Look forward to your future update which would work well between switching tabs.

**Comment by glacambre** [comment] 2018-06-08 11:14
I think this might be a duplicate of https://github.com/cmcaine/tridactyl/issues/57 .

**Closed** 2018-06-08 11:58 UTC

**Comment by homosapien97** [comment] 2020-10-03 15:20
This doesn't quite disable Tridactyl on the sites where you set ignore mode: you still get a little "ignore" bubble in the bottom right hand corner of the page, which is quite annoying when playing full-screen video.
One solution would be to display nothing in the bottom right when ignore mode is on.
Alternatively, if there's some way to completely disable the plugin on certain URLs (not just ignore mode), that would also be great.
