### ISSUE TITLE
unusual size and placement of input window

### ISSUE THREAD

**Issue by setharnold** [cmcaine/tridactyl#419] opened 2018-04-23 22:21 UTC
Hello, I hit 'o' on https://multco.us/assessment-taxation and the input and suggestions weren't at the bottom of the page, as usual, but instead on the upper left-hand corner of the page. It was perhaps one third or one quarter the width of the page, and perhaps one fifth or one sixth the height of the page.

Here's a fairly poor ascii-screenshot; the 'o' contents are in the `X` spaces, the page contents in the `.` spaces, and ` ` is blank space.

```
+--------+
|XX      |
|........|
+--------+
```

Tridactyl 1.9.5-1.9.5 on Firefox 59.0.2+build1-0ubuntu0.16.04.3

Thanks

**Comment by cmcaine** [comment] 2018-04-23 22:30
Reproducible.

Their page JS has rewritten our iframe and broken its CSS:

```html
<iframe class="cleanslate" src="moz-extension://96e03579-08f5-4672-8960-6d48accc9d24/static/commandline.html&amp;api=1&amp;player_id=vimeo-player0" id="vimeo-player0" style="height: 0px !important;"></iframe>
```

I don't think we can stop them from modifying the element but there are some other things we could do.

The build linked in #279 might work too.

**Comment by bovine3dom** [comment] 2018-05-04 23:02
Seems to be fixed in current builds. Please let us know if it isn't on your machine.

**Closed by bovine3dom** 2018-05-04 23:02 UTC
Labels: bug
