### ISSUE TITLE
Hinting through shift + f does not always open in new tab on duckduckgo

### ISSUE THREAD

**Issue by Bazalia** [cmcaine/tridactyl#497] opened 2018-05-08 07:19 UTC
When I click shift + f on duckduckgo search results page I get two hints on top of each other for each search result. One of these hints opens the link in a new tab but the other opens it in the current tab. I don't think this problem was there when I initially started using tridactyl.

**Comment by bovine3dom** [comment] 2018-05-08 07:32
Probably related to #367. The extra hints will be JavaScript which generally can't be opened in a new tab, so we fall back to clicking on them. We just need to get rid of the extra hints, probably via a site specific black list.

Thanks for reporting!

**Comment by glacambre** [comment] 2018-05-08 09:08
Perhaps we could have hints get different classes depending on what they point to and then we could have themes that give them different colors. This could help users determine whether what they're going to click on will open in a newtab or not and also help us measure whether js hints are actually useful or not.

**Comment by bovine3dom** [comment] 2018-05-08 09:59
That's a pretty good idea. We should increase the z index of non-js hints, too.

**Comment by bovine3dom** [comment] 2018-05-09 10:15
Closing as duplicate of #367.

**Closed by bovine3dom** 2018-05-09 10:15 UTC
Labels: site specific
