### ISSUE TITLE
Dev Tools Debugger no longer working

### ISSUE THREAD

**Issue by wschmrdrNS** [cmcaine/tridactyl#187] opened 2017-12-01 20:56 UTC
Opened the Firefox Developer tools on a page (I do web development as a line), went to the Debugger, and it wouldn't open at all. Tried restarting Firefox, no such luck. Tried disabling Tridactyl and opened the debugger, and it opened as expected.

**Comment by glacambre** [comment] 2017-12-01 21:15
I can't reproduce this bug on 1.7.0pre520, either by using menus or Ctrl-Shift-S to open the debugger. Do you have any other addon enabled? Specific userchrome? Does opening the debugger with Ctrl-Shift-S also fail?

**Comment by wschmrdrNS** [comment] 2017-12-01 21:22
Well, it all of a sudden started working again using F12... not sure what happened there, maybe there was another release today that made this issue OBE... I'm certainly puzzled by it.

**Comment by glacambre** [comment] 2017-12-01 21:29
That is certainly puzzling, I don't think Tridactyl could prevent the debugger from loading even if it wanted to. An update landed quite recently on AMO, this might be the reason why you're not experiencing this bug anymore.

**Comment by bovine3dom** [comment] 2017-12-01 21:36
We didn't make any changes that should have affected the debugger.

Strange things can happen when the extension is updated.

**Closed** 2017-12-04 14:39 UTC
