### ISSUE TITLE
Kill the chrome

### ISSUE THREAD

**Issue by cmcaine** [cmcaine/tridactyl#31] opened 2017-10-25 12:01 UTC
Hide or auto-hide the firefox chrome.

userChrome-minimal.css already hides the tabs, but it's possible to hide the nav-bar too[[1]].

Let's find some way to combine these styles (just concatenating them doesn't do what we want).

[1]: https://github.com/Timvde/UserChrome-Tweaks/blob/master/navbar/auto-hide.css

**Comment by cmcaine** [comment] 2017-10-25 12:19
Comments on reddit that might be useful: https://www.reddit.com/r/FirefoxCSS/comments/6xlzbs/simple_autohide_toolbars_with_fluid_animation_and/

**Comment by aplaice** [comment] 2017-10-29 20:14
First, a suggestion on how to explore Firefox's chrome css (I'm working this out myself):

1. Go to Tools > Web Developer > Browser Toolbox or use the lovely shortcut `C-A-S-i` (I think that it's slightly more convenient than inspecting chrome://browser/content/browser.xul ).

2. In the toolbox use the "inspector" tab to inspect elements and the "style editor" tab to add your own custom CSS (this is much faster than changing userChrome.css and restarting firefox) — it works just like Firefox's normal developer tools

3. Look up the definitions of the pre-set CSS variables online (e.g. [--space-above-tabbar](https://dxr.mozilla.org/mozilla-central/source/obj-x86_64-pc-linux-gnu/dist/bin/browser/chrome/browser/skin/classic/browser/browser.css#217)). Unfortunately I have no idea of how to easily find all the definitions without trawling through the entire source.

(I apologise if you're aware of all of this...)

I'm not sure exactly what degree of hiding you want, but here are several possibilities.

## A. Hide the tab bar and the nav-bar

```css
#navigator-toolbox { display: none;}
```

The tab bar and the nav-bar will both be permanently hidden, as will the menu bar (though that is usually hidden anyway).

## B. Auto-hide both tab bar and nav-bar (they only re-appear when you press C-l, F6 or the like)


```css


:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) { 
  overflow-y: hidden;
  max-height: 0px;
  min-height: 0!important;
}


```


## C. Auto-hide both tab bar and nav-bar (they only re-appear when you press C-l, F6 etc. or when you hover over the transparent 1px strip at the top)


```css


:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) { 
  overflow-y: hidden;
  max-height: 1px;
  min-height: 0!important;
  opacity: 0;
}


```


## D. Like B. but menu-bar friendly (pressing Alt will reveal the menu-bar)

```css

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) { 
  max-height: 0;
  min-height: calc(0 * var(--tab-min-height)); // I have no idea why just using 0 or 0px does not work...
}

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #TabsToolbar { 
  overflow-y: hidden;
  max-height: 0px;
  min-height: 0!important;
}

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #nav-bar { 
  overflow-y: hidden;
  max-height: 0px;
  min-height: 0!important;
}

#navigator-toolbox:not(:hover):not(:focus-within)::after {
  display: none !important;
}

```

## E. Like C. but menu-bar friendly (pressing Alt will reveal the menu-bar)

```css

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) { 
  max-height: 0;
  min-height: calc(0 * var(--tab-min-height)); // I have no idea why just using 0 or 0px does not work...
}

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #TabsToolbar { 
  overflow-y: hidden;
  max-height: 1px;
  min-height: 0!important;
  opacity: 0;
}

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #nav-bar { 
  overflow-y: hidden;
  max-height: 0px;
  min-height: 0!important;
}

#navigator-toolbox:not(:hover):not(:focus-within)::after {
  display: none !important;
}


```

(My personal favourite.)

## Notes

These have been tested only on Linux. They were strongly inspired by the [script you had linked](https://github.com/Timvde/UserChrome-Tweaks/blob/master/navbar/auto-hide.css).

I have not allowed for any "fading-in" effects / transitions as I dislike them, but if you want, they should be easy to add. Also, for these examples, the chrome will not slide over / obscure the content, but will instead work like Firefox's fullscreen mode.



Hopefully this is close to what you want.


Thank you very much for working on a replacement for Vimperator! :)

**Comment by bovine3dom** [comment] 2017-10-29 22:10
These look really really useful, thanks so much!I had no idea about most of it.                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: 29 October 2017 20:14To: tridactyl@noreply.github.comReply to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: Re: [cmcaine/tridactyl] Kill the chrome (#31)  First, a suggestion on how to explore Firefox's chrome css (I'm working this out myself):

Go to Tools > Web Developer > Browser Toolbox or use the lovely shortcut C-A-S-i  (I think that it's slightly more convenient than inspecting chrome://browser/content/browser.xul ).

In the toolbox use the "inspector" tab to inspect elements and the "style editor" tab to add your own custom CSS (this is much faster than changing userChrome.css and restarting firefox) — it works just like Firefox's normal developer tools

Look up the definitions of the pre-set CSS variables online (e.g. --space-above-tabbar). Unfortunately I have no idea of how to easily find all the definitions without trawling through the entire source.

(I apologise if you're aware of all of this...)
I'm not sure exactly what degree of hiding you want, but here are several possibilities.
A. Hide the tab bar and the nav-bar
#navigator-toolbox { display: none;}
The tab bar and the nav-bar will both be permanently hidden, as will the menu bar (though that is usually hidden anyway).
B. Auto-hide both tab bar and nav-bar (they only re-appear when you press C-l, F6 or the like)
:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) { 
  overflow-y: hidden;
  max-height: 0px;
  min-height: 0!important;
}


C. Auto-hide both tab bar and nav-bar (they only re-appear when you press C-l, F6 etc. or when you hover over the transparent 1px strip at the top)
:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) { 
  overflow-y: hidden;
  max-height: 1px;
  min-height: 0!important;
  opacity: 0;
}


D. Like B. but menu-bar friendly (pressing Alt will reveal the menu-bar)
:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) { 
  max-height: 0;
  min-height: calc(0 * var(--tab-min-height)); // I have no idea why just using 0 or 0px does not work...
}

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #TabsToolbar { 
  overflow-y: hidden;
  max-height: 0px;
  min-height: 0!important;
}

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #nav-bar { 
  overflow-y: hidden;
  max-height: 0px;
  min-height: 0!important;
}

#navigator-toolbox:not(:hover):not(:focus-within)::after {
  display: none !important;
}

E. Like C. but menu-bar friendly (pressing Alt will reveal the menu-bar)
:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) { 
  max-height: 0;
  min-height: calc(0 * var(--tab-min-height)); // I have no idea why just using 0 or 0px does not work...
}

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #TabsToolbar { 
  overflow-y: hidden;
  max-height: 1px;
  min-height: 0!important;
  opacity: 0;
}

:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #nav-bar { 
  overflow-y: hidden;
  max-height: 0px;
  min-height: 0!important;
}

#navigator-toolbox:not(:hover):not(:focus-within)::after {
  display: none !important;
}


(My personal favourite.)
Notes
These have been tested only on Linux. They were strongly inspired by the script you had linked.
I have not allowed for any "fading-in" effects / transitions as I dislike them, but if you want, they should be easy to add. Also, for these examples, the chrome will not slide over / obscure the content, but will instead work like Firefox's fullscreen mode.
Hopefully this is close to what you want.
Thank you very much for working on a replacement for Vimperator! :)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cmcaine** [comment] 2017-10-30 13:56
Thanks @aplaice!

Only problem I see is that in fullscreen mode I get a one px black line under the navbar sometimes (never the first time, sometimes appears if you linger on the bar, always appears if you focus and unfocus the navbar a few times).

Here's my merge of your option E and Olie's existing work:

```css
/* @aplaice's contributions:

   auto-hides the tab and navigation bar in a similar way to fullscreen mode
*/

/* Hide grey container box */
:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) { 
  max-height: 0;
  min-height: calc(0 * var(--tab-min-height)); /* I have no idea why just using 0 or 0px does not work... */
}

/* Auto hide tab bar

   (Overridden by bovine3dom's unconditional banning of tab bar)
*/
:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #TabsToolbar { 
  overflow-y: hidden;
  max-height: 1px;
  min-height: 0!important;
  opacity: 0;
}

/* Auto hide main bar */
:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #nav-bar { 
  overflow-y: hidden;
  max-height: 0px;
  min-height: 0!important;
} 

/* @bovine3dom's contributions: hide tabs, window decoration; thin nav-bar */

/* Make nav-bar thinner */
#nav-bar{
    padding-top: 1px !important;
    padding-bottom: 0 !important;
}

/* We need more padding when maximised (Olie, please explain!) */
#main-window[sizemode="maximized"] #nav-bar{    
    padding-top: 7px !important;
}

/* Partial removal of black bottom 1px line shown in fullscreen mode */
#navigator-toolbox::after { display: none !important; }

/* Hide tabs */
#TabsToolbar { visibility: collapse; }

/* Remove window buttons (Close, Minimize, Fullscreen) */
#titlebar { display: none !important; }
#TabsToolbar .titlebar-placeholder { display: none !important; }
```

**Comment by cmcaine** [comment] 2017-10-30 14:04
How on earth did you come up with this bit, though!?

```css
  min-height: calc(0 * var(--tab-min-height)); /* I have no idea why just using 0 or 0px does not work... */
```

**Comment by bovine3dom** [comment] 2017-10-30 14:26
FWIW: the browser toolbox is not available unless you enable "addon debugging" in about:debugging.

Additionally, the above CSS mostly works on Windows but does not show on hover.

**Comment by aplaice** [comment] 2017-10-30 16:42
> Thanks @aplaice!

I'm glad to be of use.

> Only problem I see is that in fullscreen mode I get a one px black line under the navbar sometimes (never the first time, sometimes appears if you linger on the bar, always appears if you focus and unfocus the navbar a few times).

Unfortunately, I haven't been able to reproduce that with either E or your merge, on nightly or 56 (I tested it both in my tiling window manager and XFCE). When I press `F6` a couple of times, I do get a dotted line around the entire content area, but I don't think that's what you mean (plus it vanishes when I press any other key).

> Here's my merge

One slight problem is that because the tab bar is now permanently hidden, it seems to be impossible to access the nav bar by hovering (since in E, I relied on the tab bar being 1 px high and transparent (0 opacity)). If you still can, then please tell me. 

I think that this can be remedied by instead making the nav-bar transparent and of non-zero height:

<details>

## F. Transparent nav-bar of non-zero height (merge)

```css
/* @aplaice's contributions:

   auto-hides the tab and navigation bar in a similar way to fullscreen mode
*/

/* Hide grey container box */
:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) { 
  max-height: 0;
  min-height: calc(0px); /* I have no idea why just using 0 or 0px does not work... */
}

/* Auto hide tab bar

   (Overridden by bovine3dom's unconditional banning of tab bar)
*/
:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #TabsToolbar { 
  overflow-y: hidden;
  max-height: 1px;
  min-height: 0!important;
  opacity: 0;
}

/* Auto hide main bar */
:root:not([customizing]) #navigator-toolbox:not(:hover):not(:focus-within) #nav-bar { 
  overflow-y: hidden;
  max-height: 1px;
  min-height: 0!important;
  opacity: 0;
} 

/* @bovine3dom's contributions: hide tabs, window decoration; thin nav-bar */

/* Make nav-bar thinner */
#nav-bar{
    padding-top: 1px !important;
    padding-bottom: 0 !important;
}

/* We need more padding when maximised (Olie, please explain!) */
#main-window[sizemode="maximized"] #nav-bar{
    padding-top: 7px !important;
}

/* Partial removal of black bottom 1px line shown in fullscreen mode */
#navigator-toolbox::after { display: none !important; }

/* Hide tabs */
#TabsToolbar { visibility: collapse; }

/* Remove window buttons (Close, Minimize, Fullscreen) */
#titlebar { display: none !important; }
#TabsToolbar .titlebar-placeholder { display: none !important; }
```

</details>


> How on earth did you come up with this bit, though!?

By trying to determine why [the previously linked CSS auto-hiding the nav-bar](https://github.com/Timvde/UserChrome-Tweaks/blob/master/navbar/auto-hide.css) doesn't have the problem that I do and checking what is the minimal CSS that works. (Actually, now that I check `calc(0px);` also works — I swear that it didn't yesterday...)


FWIW, after testing with a window manager that has title bars, where the edge of the screen does not coincide with the edge of the area managed by firefox, so just pushing the mouse as far up as possible doesn't work, the 1px-high area for hovering is rather narrow, so depending on what you think, it might be preferable to make this slightly wider.

The complications on Windows might also appear on Linux once client-side decorations are phased in.

**Comment by bovine3dom** [comment] 2017-11-06 20:59
Somewhat related: https://wiki.mozilla.org/WebExtensions/TabHiding is collating information on Mozilla's approach to hiding some the tab bar.

**Comment by bovine3dom** [comment] 2017-11-08 11:27
The current minimal CSS doesn't allow windows to be dragged around in Windows.

I suspect we could fix it by only hiding the URL bar when the window is maximised.

**Comment by cmcaine** [comment] 2017-11-08 15:36
```css
:root:not([customizing]) #main-window:not([sizemode="maximized"]) #navigator-toolbox:not(:hover):not(:focus-within) #nav-bar {
```

That work?

**Comment by robehickman** [comment] 2017-11-30 14:44
"I suspect we could fix it by only hiding the URL bar when the window is maximised."

Need to make sure this works properly with tiling window managers on X11 if given as a generic solution, they don't really have a concept of 'maximised' as far as I know. I guess it depends what meta-data they set on the window, I don't know how X works.

**Comment by cmcaine** [comment] 2017-12-11 14:11
@bovine3dom and I both exclusively use tiling window managers on the machines that we develop on, so I wouldn't worry about us forgetting :)

**Comment by bodograumann** [comment] 2018-04-16 17:03
Hey, thanks for the great work!

One thing that still could be improved in https://github.com/cmcaine/tridactyl/blob/master/src/static/userChrome-minimal.css:
Currently if you happen to move the mouse beyond the top of the window, the location bar will be completely shown and immediatly hidden again. I tried adding a `transition` attribute to `userChrome.css` but that did not really take effect. Maybe somebody else has better luck.

@robehickman: Awesome WM at least, has notions of maximized, as well as fullscreen windows. The latter is the same as pressing F11 in firefox.

**Comment by bovine3dom** [comment] 2018-04-27 23:59
#407 is pretty close to being done.

I'd appreciate some help with thinking of various options and how they translate into snippets of CSS.

**Comment by bovine3dom** [comment] 2018-05-18 14:05
Closing since #407 is merged. Still happy to accept contributions towards `guiset`.

**Closed by bovine3dom** 2018-05-18 14:05 UTC
Labels: enhancement, help wanted
