### ISSUE TITLE
Blank page on https://codeforces.com/

### ISSUE THREAD

**Issue by FardaleM** [cmcaine/tridactyl#722] opened 2018-06-21 10:47 UTC
If I enable tridactyl I can not use [https://codeforces.com/](https://codeforces.com/) because I just see a blank page.

**Comment by bovine3dom** [comment] 2018-06-21 13:45
Duplicate of #279.

Can be fixed with the totally undocumented `set noiframeon https://codeforces.com/`.

**Closed by bovine3dom** 2018-06-21 13:45 UTC

**Comment by UnkwUsr** [comment] 2020-03-13 13:30
Why is this not fixed after 2 years? Bug still exist. Isn't a tridactyl problem?

**Comment by glacambre** [comment] 2020-03-13 15:15
@UnkwUsr This issue has been closed because a workaround has been provided (the workaround is now `:seturl noiframe true` btw) and because there are other issues tracking this bug (mainly https://github.com/tridactyl/tridactyl/issues/639).
It hasn't been fixed because nobody cared enough to fix it - if you want to try to do it yourself feel free to ask questions here or on matrix, we'll be very happy to help you start hacking on Tridactyl! :)

**Comment by bovine3dom** [comment] 2020-03-13 16:06
There's a broken PR that tries to fix it - https://github.com/tridactyl/tridactyl/pull/1331 - fixing that PR would probably be the place to start :)
