### ISSUE TITLE
Support :set! command from Pentadactyl

### ISSUE THREAD

**Issue by maln0ir** [cmcaine/tridactyl#526] opened 2018-05-13 09:22 UTC
In Pentadactyl `:set!` command allowed to change browser settings (about:config). I used that command in my `.pentadactylrc` to set my own configuration and also store it in vcs-friendly way.

It would be nice to get this _back_ :)

**Comment by bovine3dom** [comment] 2018-05-13 09:34
Easy in theory: we just need to make/edit user.js http://kb.mozillazine.org/User.js_file

The tricky part would be if we want to have any kind of checking that values are supported and their types, etc.

**Comment by bovine3dom** [comment] 2018-05-13 12:31
Duplicate of #468 :)

**Closed by bovine3dom** 2018-05-13 12:31 UTC
Labels: good first issue, help wanted, nativemessenger
