### ISSUE TITLE
Tridactyl do not work in Firefox reader mode

### ISSUE THREAD

**Issue by mayanksuman** [cmcaine/tridactyl#299] opened 2018-01-29 05:46 UTC
Tridactyl (version 1.7.3) shortcuts do not work in reader mode in Firefox 58. I have checked movement shortcuts (h/j/k/l) and tab navigation shortcut (gt). Neither of them is working.

Operating system: Debian Testing 64 bit
Web Browser: Firefox 58
Tridactyl Version: 1.7.3

**Comment by johnbeard** [comment] 2018-01-29 08:56
Duplicate of #102 - this is currently a limitation of the Web Extension API.

**Closed** 2018-01-29 10:01 UTC
