### ISSUE TITLE
[Windows] :installnative powershell command doesn't work

### ISSUE THREAD

**Issue by pinetreegator** [cmcaine/tridactyl#656] opened 2018-06-07 17:39 UTC
Hello, I'm new to using this addon. I tried using the powershell script that the :installnative command copies to clip board but it fails instantly. This is the output:

> PS C:\Users\PTG> Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/cmcaine/tridactyl/master/native/win_install.ps1'))
[+] Looking for Python 3 ...
	-Python 3 found at: C:\Windows\py.exe
[+] Preparing C:\Users\PTG\.tridactyl ...
	- C:\Users\PTG\.tridactyl exists, moving on ...
	- Testing C:\Users\PTG\.tridactyl was successful!
	- Creating C:\Users\PTG\.tridactyl was successful!
[+] Downloading https://raw.githubusercontent.com/cmcaine/tridactyl/master/native_main.py?1528391799.41584 ...
Invoke-Webrequest StatusCode: 404
Invoke-Webrequest StatusDescription: Not Found
[+] Downloading failed, quitting ...

>

**Comment by glacambre** [comment] 2018-06-07 19:35
Looks like we're missing "native" between "master" and "native_main.py" in the URL the native messenger is downloaded from.

Also I don't understand why the current date is appended as a GET parameter. @gsbabil is this required by github's API?

**Comment by bovine3dom** [comment] 2018-06-07 20:03
The problem is around here somewhere: https://github.com/cmcaine/tridactyl/blob/690ecc92bd60a7f5fe1c029a12c7d28bc7ec227b/native/win_install.ps1#L205

I think this might be my fault.

**Comment by gsbabil** [comment] 2018-06-08 05:00
@bovine3dom

> The problem is around here somewhere:
> $global:MessengerFilesHttpUriBase, 

Indeed. The download URL was being constructed incorrectly _i.e._
`$git_repo_branch = "master"` is enough, `cmcaine/master` isn't
neded. I tend to namespace my branches with `gsbabil`, which may
have misled you.

Anyhow, I just submitted #658 which should fix this. Thanks.


@glacambre

> Also I don't understand why the current date is appended as a GET
> parameter. @gsbabil is this required by github's API?

Appending epoch in the query-string should help getting around
intermediate caching proxies between the user and Github. The epoch
without a field/key-name is usually silently dropped by the server,
and wasn't contributing to the problem in this instance.

This is _not_ needed Github by API (we aren't actually using any here),
but my two-cents would be to keep it there.

Thanks.

**Comment by bovine3dom** [comment] 2018-06-08 09:06
@pinetreegator should be fixed in #658. Please confirm :)

**Comment by pinetreegator** [comment] 2018-06-08 23:28
Just want to confirm that the fix does work. Thank you

**Comment by Susexe** [comment] 2018-07-12 21:23
Install a newer version of Windows Management Framework if someone encounters the following error:

> Invoke-WebRequest Exception: System.Management.Automation.CommandNotFoundException The term 'Invoke-WebRequest' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by Susexe** [comment] 2018-07-12 21:31
Hm, even though it installed correctly, `:native`command shows no sign of native messenger.

**Comment by bovine3dom** [comment] 2018-07-12 21:33
Could you open a new issue, @Susexe, and we can try to help you debug it?

**Closed** 2018-07-12 21:34 UTC

**Comment by bovine3dom** [comment] 2018-07-12 21:50
> Install a newer version of Windows Management Framework if someone encounters the following error:

is a duplicate of/related to #793.
