### ISSUE TITLE
Key bindings do not support the control key modifier

### ISSUE THREAD

**Issue by alexconst** [cmcaine/tridactyl#250] opened 2017-12-23 22:49 UTC
If it's possible to do so I couldn't find a way. I tried both `bind <C-p> tabprev` (as in .vimperatorrc) and attempted `bind control-p tabprev` but it didn't do anything, nor did it pop an error message.
Shift works fine, but that's an easy one.
I also looked at https://github.com/cmcaine/tridactyl/blob/master/src/config.ts but couldn't find anything relevant.

Would it be possible to please update the README.md file to 1) either include information on how to do this or 2) an ETA to add support for this?

Thanks

**Comment by bovine3dom** [comment] 2017-12-23 22:59
Duplicate of #41. @cmcaine was working on this last on the keyseq branch, he's the best person to ask for an ETA.

The README has an FAQ section which does state that modifiers cannot be bound. Is it unclear or should it be moved further up the document?

**Comment by alexconst** [comment] 2017-12-24 13:11
Apologies for missing it :(

I made a few changes here https://github.com/cmcaine/tridactyl/pull/251
I hope it is alright.

**Comment by bovine3dom** [comment] 2017-12-24 14:44
That's made it a bit clearer. Thanks!

**Closed** 2017-12-24 14:44 UTC
