### ISSUE TITLE
hint mode don't work on facebook.com, not always jumps properly

### ISSUE THREAD

**Issue by pholat** [cmcaine/tridactyl#169] opened 2017-11-30 14:54 UTC
When pressed `f` on www.facebook.com page there are no hints and binds stop working. 

When pressed `f` on www.google.com new tabs are being created and I'm left out on the google search page, while on other pages I get the result in current tab.

This was seen on Windows 10, where in my case Firefox Quantum is not always reliable. I'll test it on more stable Linux and add result here too.

**Comment by bovine3dom** [comment] 2017-11-30 15:02
Possibly a duplicate of #168.

**Comment by pholat** [comment] 2017-11-30 15:19
Thanks, confirmed it is a duplicate - I was a few min late creating the case. When waited long enough on #168 it's the same as www.facebook.com issue.

**Comment by bovine3dom** [comment] 2017-11-30 15:20
Thanks for reporting it anyway!

**Closed** 2017-11-30 15:20 UTC

**Comment by bovine3dom** [comment] 2017-11-30 15:40
@pholat it should be fixed from beta 507.
