### ISSUE TITLE
Hinting conflicts with key bindings

### ISSUE THREAD

**Issue by larsks** [cmcaine/tridactyl#173] opened 2017-11-30 16:32 UTC
I used `f` to enter hint mode.  One of the links had the hint `D`.  I pressed `D` and...the tab was closed.  Hint mode should probably be a distinct mode in which existing key bindings are ignored.

In hint mode, `ESC` should probably cancel hint mode and return to normal mode.

**Comment by bovine3dom** [comment] 2017-11-30 17:11
I believe this is really a duplicate of #114 in disguise.

Hinting is a separate mode, and the bindings don't exist. Regarding the existence uppercase hints, see #130.

**Closed by bovine3dom** 2017-11-30 17:11 UTC

**Comment by larsks** [comment] 2017-11-30 18:01
I'm not sure what you mean by "...and the bindings don't exist".  I mean, if I open, for example, 
https://github.com/cmcaine/tridactyl/issues/114, wait a bit, press `f` then `d`, the tab closes.  I'm neither changing the tab nor entering hint mode quickly, which I think covers both of the bullet points there.  This is reproducible every time (i.e., it doesn't seem like some sort of timing issue or anything).

Does it still sound like the same issue?

**Comment by Koushien** [comment] 2017-12-01 01:07
@larsks I can't replicate this either, even on the issue page you mentioned. Does this only happen with `d`? Can you confirm your Tridactyl `:version`?
What I believe @bovine3dom means is that the bind `d` to `tabclose` only exists in normal mode and `tabclose` has no way to be called while in hinting. It is likely the case the mode Tridactyl believes it is in is changing, hence the link to #114 which should end up solving your issue.
To help troubleshoot, you can try opening the Browser Console with Ctrl+Shift+J on Windows or Linux.
Tridactyl should emit every mode change there (e.g., `State changed! mode normal`). On `f` and without doing anything else you should only see the mode change to `hint`.

**Comment by bovine3dom** [comment] 2017-12-01 08:10
@larsks Do you have an example of a website where you experience this?

My hunch is still #114 as "wait a bit" could end up being quite a while on a heavy site or slow connection.

**Comment by larsks** [comment] 2017-12-01 19:39
Well, chalk it up as a heisenbug. While I was consistently having the problem earlier, regardless of website, a simple browser restart has made the problem go away.
