### ISSUE TITLE
Status bar is huge on some websites

### ISSUE THREAD

**Issue by utsekaj42** [cmcaine/tridactyl#289] opened 2018-01-23 09:13 UTC
On the <https://docs.anaconda.com/anaconda-cloud/user-guide/> website the status bar is almost 1/4 of the way up the page. 
![user guide anaconda documentation - mozilla firefox_005](https://user-images.githubusercontent.com/2432965/35267248-efcbeeaa-0025-11e8-8ac8-28bf56ac154a.png)

Similarly for this website, <http://kiwi.mit.edu/>

![multifidelity optimization under uncertainty multifidelity monte carlo adaptive reduced models and educational mapping professor of aeroastro at mit co-director of the mit center for computational engineering - mozilla firefox_006](https://user-images.githubusercontent.com/2432965/35267246-ec7a55b6-0025-11e8-961c-2c6981d1a2b6.png)

**Comment by bovine3dom** [comment] 2018-01-23 09:51
We've seen this before on some other sites, but I can't seem to find an issue mentioning it. It could be related to #112.

Thanks for reporting!

**Comment by cmcaine** [comment] 2018-02-03 01:58
This is a duplicate of #112.

#112 is quite easy to solve if anyone feels like giving it a go. Just use e.g. cleanslate.css and adjust the iframe css.

**Comment by bovine3dom** [comment] 2018-02-14 11:31
Fixed by @johnbeard in #306

**Closed by bovine3dom** 2018-02-14 11:31 UTC
