### ISSUE TITLE
Tridactyl not working on lodash doc page

### ISSUE THREAD

**Issue by wschmrdrNS** [cmcaine/tridactyl#184] opened 2017-12-01 18:03 UTC
Open the lodash documentation at https://lodash.com/docs/4.17.4 .
Attempt to issue a tridactyl command (such as the : to open the command line).

The command line doesn't show. I've also tried some other binds (t, s, S) and those don't work either.

(there was some previous stuff here about iframes, but I just noticed that you're the iframe, so taking it out)

**Comment by glacambre** [comment] 2017-12-01 18:11
Isn't this a duplicate of https://github.com/cmcaine/tridactyl/issues/35 https://github.com/cmcaine/tridactyl/issues/67 and https://github.com/cmcaine/tridactyl/issues/122 ?

**Comment by bovine3dom** [comment] 2017-12-01 19:19
Yep, duplicate of #109. Thanks for reporting it!

**Closed by bovine3dom** 2017-12-01 19:19 UTC
