### ISSUE TITLE
Sometimes cannot use Tridactyl on an image page

### ISSUE THREAD

**Issue by johnbeard** [cmcaine/tridactyl#113] opened 2017-11-22 21:35 UTC
To reproduce:

* Visit an image page (doesn't have to be a data: image, but they wouldn't work anyway (?))
* E.g. https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Vimlogo.svg/1022px-Vimlogo.svg.png
* Press 'H' to go back, or try to open the command line
* Nothing happens

I'm assuming this is another WebExtension limitation, but it's not mentioned in the "where it doesn't work" list. Is there a separate API discussion to be had about it?

**Comment by bovine3dom** [comment] 2017-11-22 21:37
That link works for me: https://i.imgur.com/iwGK7mD.png

I have experienced this before, though, so I know it is a real issue...

**Comment by johnbeard** [comment] 2017-11-22 21:48
Huh, you're right, it working for me sometimes as well, though I can't immediately see a pattern to when it doesn't work. Sorry for jumping to conclusions about WebExts!

**Comment by Bzly** [comment] 2017-11-23 00:19
Hmmmm. I've had quite a play around for the last 10 minutes and I haven't been able to replicate it.

(This (https://i.imgur.com/74i2Qtu.png) part does hide the buffers and hint labels, though). 
URL: https://commons.wikimedia.org/wiki/File:Vimlogo.svg#/media/File:Vimlogo.png

**Comment by johnbeard** [comment] 2017-11-23 02:53
How about this image, I can't get it to ever work: https://raw.githubusercontent.com/liuchengxu/img/master/space-vim/space-vim-cterm.png

Doesn't seem to be to do with the size, as bigger images can (usually do) work.

**Comment by glacambre** [comment] 2017-11-28 18:24
I think this is the same issue as https://github.com/cmcaine/tridactyl/issues/109 .
When a website has something like `Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox`, Tridactyl won't work. This can be 100% reproduced by running the following commands:
```shell
echo -e 'HTTP/1.0 200 OK\nContent-Security-Policy: default-src ''none''; style-src ''unsafe-inline''; sandbox\n\n\nThis kills the tridactyl\n' | nc -l -p 8080
```
Then connect to http://localhost:8080, kill nc and you won't be able to use Tridactyl to leave the tab anymore.

If you take a look at the headers returned by Github for johnbeard's link, you'll notice the CSP is the same as the one I mentioned.

**Comment by bovine3dom** [comment] 2018-04-12 15:36
Closing as duplicated of #109.

**Closed by bovine3dom** 2018-04-12 15:36 UTC

**Comment by yarub123** [comment] 2023-02-11 07:40
@bovine3dom ;m and ;M haven't been working for me for nearly 1-2 years now, for reverse (Google) image searching. 

Did they work before? Yes. 

(2/10/23, 11:40 PM)
