### ISSUE TITLE
Support "Alt" key bindings

### ISSUE THREAD

**Issue by wnereiz** [cmcaine/tridactyl#293] opened 2018-01-25 03:08 UTC
Currently binding "alt" key is not supported. But it is available on other similar project like vimium. Would you consider to add it. Or are there any difficulties to add it?

**Comment by Koushien** [comment] 2018-01-25 03:14
Duplicate of #41

**Comment by bovine3dom** [comment] 2018-01-25 08:40
@wnereiz, thanks for your interest. I'll close this as it is a duplicate.

There is no real problem - the code to implement this is sitting, mostly finished, in the keyseq branch. It just needs some brave soul to plumb it in to the parsers.

**Closed by bovine3dom** 2018-01-25 08:40 UTC
