### ISSUE TITLE
support for ctrl+O and ctrl-I for history navigation

### ISSUE THREAD

**Issue by houqp** [cmcaine/tridactyl#110] opened 2017-11-22 19:18 UTC
Hi!

Tridactyl meets most of my vimperator needs except support for going back/forward in history for current tab. Is there any plan to add support for this in the near future? If not, could someone give me a pointer on where to start to implement this feature?

Keep up with the great work :)

**Comment by bovine3dom** [comment] 2017-11-22 19:23
Hi, we don't support modifiers in normal mode yet. You could just bind it to i and o if that helps, so `bind i back` and `bind o forward`.

(by default, it is bound to H and L).

Supporting modifiers well requires a quite big rewrite of the parser. I believe @cmcaine has some uncommitted code that has started to do that.

**Comment by bovine3dom** [comment] 2017-11-26 14:57
Duplicate of #41

**Closed by bovine3dom** 2017-11-26 14:57 UTC
