### ISSUE TITLE
One-pixel bar underneath command-bar

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [cmcaine/tridactyl#442] opened 2018-04-26 21:23 UTC
This is most noticeable in the "dark" theme.

![ss1](https://user-images.githubusercontent.com/200/39332763-11918e78-496e-11e8-8abc-8c1c5d5f95bc.png)

![ss1 copy](https://user-images.githubusercontent.com/200/39332773-1893cefc-496e-11e8-8397-2419acacebe1.png)

**Comment by bovine3dom** [comment] 2018-04-26 21:25
This is probably a duplicate of #26.

Thanks for reporting it.

**Comment by ELLIOTTCABLE** [comment] 2018-04-26 22:59
On hiDPI here, as well, if that helps!

**Comment by bovine3dom** [comment] 2018-05-05 13:18
I might have fixed it. I was finding it hard to reproduce - it only happened with certain window sizes.
I haven't been able to reproduce it since that commit.

**Comment by bovine3dom** [comment] 2018-05-05 13:30
I can't reproduce it again, and this time it's definitely for real. 100%. :1st_place_medal:

**Closed** 2018-05-05 13:30 UTC

**Comment by bovine3dom** [comment] 2018-05-12 23:38
@ELLIOTTCABLE it's already in the betas, and stable too... I guess that means it isn't fixed after all? What version are you using?

**Comment by ELLIOTTCABLE** [comment] 2018-05-13 18:58
Oh, man. Scratch that; it works now! I guess it just hadn't self-updated. `<3`
