### ISSUE TITLE
Dark theme doesn't affect mode-indicator

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [cmcaine/tridactyl#443] opened 2018-04-26 21:24 UTC
Title!

(Forgive my short issue message descriptions; re-learning to type in Colemak 🤣)

**Comment by bovine3dom** [comment] 2018-04-26 22:08
Duplicate of #415 (took me a while to find the issue and I knew it was there, so I forgive you :) )

**Closed by bovine3dom** 2018-04-26 22:08 UTC
