### ISSUE TITLE
Mouse Events In Lower Section of Window Do Not Work

### ISSUE THREAD

**Issue by R030t1** [cmcaine/tridactyl#178] opened 2017-12-01 07:12 UTC
I just disabled/enabled Tridactyl to check. It seems like there is a ghost overlay blocking mouse events to the currently loaded page.

**Comment by bovine3dom** [comment] 2017-12-01 08:12
Duplicate of #170. Thanks for taking the time to report it : )

**Closed** 2017-12-01 08:12 UTC
