### ISSUE TITLE
Commandline + completions sometimes covers up the page even when it is hidden.

### ISSUE THREAD

**Issue by bovine3dom** [cmcaine/tridactyl#170] opened 2017-11-30 15:41 UTC
I haven't worked out how to reproduce this - I only ever notice it on GitHub where there are lots of buttons to click in the bottom third of the screen.

**Comment by petermehle** [comment] 2017-11-30 16:16
It also happened on coursera.org, I just wanted it to report it. I cant reproduce it, it just happens randomly

**Comment by Koushien** [comment] 2017-12-01 01:53
Not sure how the frames cover the page even if they're hidden: cmdline&completions _should be hidden_ but are still visible? Does it consume the height of the window or only as many completions as you had? Screenshots? Can you get out of this without refreshing, restarting Tridactyl or closing Firefox? I'm guessing completions were generated at some point you had the page open (e.g., `:buffer `) and it's not just happening while idling or scrolling in the page?
@petermehle Is that on any arbitrary page on coursera.org or just the frontpage?

**Comment by petermehle** [comment] 2017-12-01 08:12
I think it happens on every page. I noticed it on frontpage and on quiz pages. As soon as I open commandline (does not matter how it is opened) and execute a command (if you just open and close it does not stay), it stays there until page is refreshed! It covers only the height of completions, not the whole window.

**Comment by Koushien** [comment] 2017-12-01 08:18
Can you confirm you cannot Shift+Esc to return to normal functionality?

**Comment by petermehle** [comment] 2017-12-01 08:36
No, only refresh

**Comment by Koushien** [comment] 2017-12-01 09:03
And it's only obstructing you visually in addition to blocking mouse events in the area it covers?
I'm heading off now, but some things to try that I would find useful hints since I don't get this myself:
1) use ctrl+m to process commandline; does this still occur? If not, there's some weird interaction with Enter.
2) if you're building tridactyl: in `commandline_frame.ts`, inside the function `hide_and_clear()`, can you add `completionsDiv = ""` in a new line after `activeCompletions = undefined` and rebuild/reload? If your issue doesn't persist after this addition, then our normal clearing process doesn't delete every completion.
3) I think this is more likely than 2, the call to `hide()` never makes it to `commandline_content.ts`; just add a `console.log("unique string")` to `hide()` which you should notice in the Browser Console (Ctrl+Shift+J in Linux/Windows) everytime the commandline is processed.

**Comment by petermehle** [comment] 2017-12-01 09:14
It does not obstruct visually, it is not visible. It is blocking the mouse events and you can see it with hints. If you press 'f', it visible and it has assigned shortcut.

**Comment by petermehle** [comment] 2017-12-01 09:23
![coursera](https://user-images.githubusercontent.com/1147046/33476261-44da5502-d679-11e7-92b6-902fbc5b5400.png)

**Comment by petermehle** [comment] 2017-12-01 09:32
Facebook has the same problem

**Comment by azuwis** [comment] 2017-12-01 09:42
Step to reproduce:

1. :tabopen test
2. :tabopen test
3. press ctrl+c
4. gT

**Closed** 2017-12-01 12:13 UTC
