### ISSUE TITLE
Infinite extended hints mode

### ISSUE THREAD

**Issue by reversebreak** [cmcaine/tridactyl#691] opened 2018-06-17 04:38 UTC
Pentadactyl (and Vimperator IIRC) had extended hints modes that didn't stop upon using it once.
This is most useful for opening things in a background tab repeatedly, such as the image hint or the link hint.  In effect, you could repeatedly type hints on the page and open a dozen links in succession for loading in background tabs.
I've looked in the help files, and can't seem to find a way to trigger this behaviour.
This used to be a core part of my workflow, and I'd love to have it back again.

**Comment by bovine3dom** [comment] 2018-06-17 09:00
Duplicate of #353 :)

It's on our to-do list - this is actually one of the things I miss most from Vimperator so it will get done eventually...

**Closed by bovine3dom** 2018-06-17 09:00 UTC

**Comment by reversebreak** [comment] 2018-06-17 09:03
Apologies.  I did search the issues before posting!  I must have missed that one.
